Integrado/config/routes.rb
Integrado::Application.routes.draw do
  get "login/index"

  root 'login#index'

 post 'login' => 'login#login'

  resources :cadastro_usuarios

  resources :agendamentos

  resources :usuarios
end

Integrado/app/models/agendamento.rb
class Agendamento < ActiveRecord::Base
end

Integrado/app/models/cadastro_usuario.rb
class CadastroUsuario < ActiveRecord::Base

	  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:login]

	validates :senha, presence: true, length: { minimum: 6 }
	validates :password_digest, presence: true, length: { minimum: 6 }
end

Integrado/app/models/usuario.rb
class Usuario < ActiveRecord::Base	
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => {email: true, login: false}
	validates :nome, presence: true, :uniqueness => true
	validates :senha, presence: true
	validates :password_digest, presence: true

	def authenticate(username, password)
		if self.nome == username && self.senha == password
	 		self
		end
	end
end

Integrado/app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :set_agendamento, only: [:show, :edit, :update, :destroy]

  # GET /agendamentos
  # GET /agendamentos.json
  def index
    @agendamentos = Agendamento.all
  end

  # GET /agendamentos/1
  # GET /agendamentos/1.json
  def show
  end

  # GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
  end

  # GET /agendamentos/1/edit
  def edit
  end

  # POST /agendamentos
  # POST /agendamentos.json
  def create
    @agendamento = Agendamento.new(agendamento_params)

    respond_to do |format|
      if @agendamento.save
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully created.' }
        format.json { render action: 'show', status: :created, location: @agendamento }
      else
        format.html { render action: 'new' }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendamentos/1
  # PATCH/PUT /agendamentos/1.json
  def update
    respond_to do |format|
      if @agendamento.update(agendamento_params)
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamentos/1
  # DELETE /agendamentos/1.json
  def destroy
    @agendamento.destroy
    respond_to do |format|
      format.html { redirect_to agendamentos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento
      @agendamento = Agendamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agendamento_params
      params.require(:agendamento).permit(:dataHora, :idQuadra, :usuario_registroUsuario)
    end
end

Integrado/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Integrado/app/controllers/cadastro_usuarios_controller.rb
class CadastroUsuariosController < ApplicationController
  before_action :set_cadastro_usuario, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_usuarios
  # GET /cadastro_usuarios.json
  def index
    @cadastro_usuarios = CadastroUsuario.all
  end

  # GET /cadastro_usuarios/1
  # GET /cadastro_usuarios/1.json
  def show
  end

  # GET /cadastro_usuarios/new
  def new
    @cadastro_usuario = CadastroUsuario.new
  end

  # GET /cadastro_usuarios/1/edit
  def edit
  end

  # POST /cadastro_usuarios
  # POST /cadastro_usuarios.json
  def create
    @cadastro_usuario = CadastroUsuario.new(cadastro_usuario_params)

    respond_to do |format|
      if @cadastro_usuario.save
        format.html { redirect_to @cadastro_usuario, notice: 'Cadastro usuario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cadastro_usuario }
      else
        format.html { render action: 'new' }
        format.json { render json: @cadastro_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_usuarios/1
  # PATCH/PUT /cadastro_usuarios/1.json
  def update
    respond_to do |format|
      if @cadastro_usuario.update(cadastro_usuario_params)
        format.html { redirect_to @cadastro_usuario, notice: 'Cadastro usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cadastro_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_usuarios/1
  # DELETE /cadastro_usuarios/1.json
  def destroy
    @cadastro_usuario.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_usuario
      @cadastro_usuario = CadastroUsuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_usuario_params
      params.require(:cadastro_usuario).permit(:nome, :registroUsuario, :emailUsuario, :senha, :telefone, :password_digest)
    end
end

Integrado/app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index

	end

	def login
		@user = Usuario.where(:nome => params[:login][:nome], :senha => params[:login][:senha]).first

		if @user.nil?
			redirect_to login_index_path
		elsif @user.authenticate(@user.nome, @user.senha )
			redirect_to usuarios_path, :notice => "Logado com Sucesso!"
		end
	end
end

Integrado/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @user = Usuario.find(params[:id])
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :senha)
    end
end

Integrado/app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

Integrado/app/helpers/application_helper.rb
module ApplicationHelper
end

Integrado/app/helpers/cadastro_usuarios_helper.rb
module CadastroUsuariosHelper
end

Integrado/app/helpers/login_helper.rb
module LoginHelper

	def current_user
    @current_user ||= User.find_by(nome: login[:nome])
  end

	def logged_in?
		!current_user.nil?
	end
end

Integrado/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Integrado/app/views/agendamentos/_form.html.erb
<%= form_for(@agendamento) do |f| %>
  <% if @agendamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agendamento.errors.count, "error") %> prohibited this agendamento from being saved:</h2>

      <ul>
      <% @agendamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dataHora %><br>
    <%= f.datetime_select :dataHora %>
  </div>
  <div class="field">
    <%= f.label :idQuadra %><br>
    <%= f.number_field :idQuadra %>
  </div>
  <div class="field">
    <%= f.label :usuario_registroUsuario %><br>
    <%= f.text_field :usuario_registroUsuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Integrado/app/views/agendamentos/edit.html.erb
<h1>Editing agendamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @agendamento %> |
<%= link_to 'Back', agendamentos_path %>

Integrado/app/views/agendamentos/index.html.erb
<h1>Listing agendamentos</h1>

<table>
  <thead>
    <tr>
      <th>Datahora</th>
      <th>Idquadra</th>
      <th>Usuario registrousuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @agendamentos.each do |agendamento| %>
      <tr>
        <td><%= agendamento.dataHora %></td>
        <td><%= agendamento.idQuadra %></td>
        <td><%= agendamento.usuario_registroUsuario %></td>
        <td><%= link_to 'Show', agendamento %></td>
        <td><%= link_to 'Edit', edit_agendamento_path(agendamento) %></td>
        <td><%= link_to 'Destroy', agendamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agendamento', new_agendamento_path %>

Integrado/app/views/agendamentos/new.html.erb
<h1>New agendamento</h1>

<%= render 'form' %>

<%= link_to 'Back', agendamentos_path %>

Integrado/app/views/agendamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datahora:</strong>
  <%= @agendamento.dataHora %>
</p>

<p>
  <strong>Idquadra:</strong>
  <%= @agendamento.idQuadra %>
</p>

<p>
  <strong>Usuario registrousuario:</strong>
  <%= @agendamento.usuario_registroUsuario %>
</p>

<%= link_to 'Edit', edit_agendamento_path(@agendamento) %> |
<%= link_to 'Back', agendamentos_path %>

Integrado/app/views/cadastro_usuarios/_form.html.erb
<%= form_for(@cadastro_usuario) do |f| %>
  <% if @cadastro_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadastro_usuario.errors.count, "error") %> prohibited this cadastro_usuario from being saved:</h2>

      <ul>
      <% @cadastro_usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :emailUsuario %><br>
    <%= f.text_field :emailUsuario %>
  </div>
   <div class="field">
    <%= f.label :senha %><br>
    <%= f.password_field :senha %>
  </div>
   <div class="field">
    <%= f.label :confirmacao_senha %><br>
    <%= f.password_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.number_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Integrado/app/views/cadastro_usuarios/edit.html.erb
<h1>Editar usuário</h1>

<%= render 'form' %>

<%= link_to 'Back', login_index_path %>

Integrado/app/views/cadastro_usuarios/index.html.erb
  <table>
  <thead>
  <tr>
    <td>Nome</td>
    <td>Registro Usuário</td>
    <td>Email</td>
    <td>Senha</td>
    <td>Confirme a sua senha</td>
    <td>Telefone</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </thead>

  <tbody>
  <% @cadastro_usuarios.each do |cadastro_usuario| %>
    <tr>
      <td><%= cadastro_usuario.nome %></td>
      <td><%= cadastro_usuario.emailUsuario %></td>
      <td><%= cadastro_usuario.senha %></td>
      <td><%= cadastro_usuario.password_digest %></td>
      <td><%= cadastro_usuario.telefone %></td>
    </tr>
  <% end %>
  </tbody>
  </table>

  <br>

  <%= link_to 'Cadastrar!', new_cadastro_usuario_path %>

Integrado/app/views/cadastro_usuarios/new.html.erb
<head>
      <title>Cadastro</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= stylesheet_link_tag "style2" %>
      <link rel="shortcut icon" type="image/x-icon" href="/assets/images/icone.png" />
</head>

<body>
        <div class="tudo" id="signup">
        <div>
        <h3>Faça seu cadastro:</h3>


	<%= render 'form' %>

	<%= link_to 'Back', login_index_path %>
        </div>
        </div>
</body>

Integrado/app/views/cadastro_usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cadastro_usuario.nome %>
</p>

<p>
  <strong>Email usuário:</strong>
  <%= @cadastro_usuario.emailUsuario %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @cadastro_usuario.senha %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cadastro_usuario.telefone %>
</p>

<%= link_to 'Edit', edit_cadastro_usuario_path(@cadastro_usuario) %> |
<%= link_to 'Back', cadastro_usuarios_path %>

Integrado/app/views/login/index.html.erb
<head>
        <title>Agendamento de Quadras CEAF</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= stylesheet_link_tag "style" %>
	<link rel="shortcut icon" type="image/x-icon" href="/assets/images/icone.png" />
</head>

<body>
	<%= form_for(:login, url: login_path) do |f| %>
		<div class="tudo">	
			<div class="itemlogin">
				<%= image_tag("icone.png") %>
			</div>
			<div class="itemlogin" id="entrar"><br/>
				<label id="nome_usuario">Usuário:</label>
				<%= f.text_field :nome %><br/><br/>
				<label type="text" id="senha">Senha:</label>
				<%= f.password_field :senha %> 
				<br/><br/>
				<%= submit_tag("Log In") %><br/><br/>
			</div>
			<div class="itemlogin"><h4>Bem vindo ao Sistema de Agendamento de Quadras do CEAF!</h4></div>
		</div> 
		<%= link_to "Novo Usuário", new_cadastro_usuario_path(@usuario) %><br/>   
	<% end %>
</body>

Integrado/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.password_field :senha %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :emailUsuario %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :fotoUsuario %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.number_field :telefone %>
  </div>
  <div class="actions">
   <%= f.submit %>
  </div>
<% end %>

Integrado/app/views/usuarios/edit.html.erb
<head>
    <title>Editar perfil</title>
     <%= stylesheet_link_tag "style2" %>
     <link rel="shortcut icon" type="image/x-icon" href="/assets/images/icone.png" />
</head>

<body>
       <div class="tudo" id="edituser">
            
       <div class="pag_user">
	<h1>Editar usuário</h1>

	<%= render 'form' %>

	<%= link_to 'Back', usuarios_path %>
 	</div>	
 	</div>
</body>

Integrado/app/views/usuarios/index.html.erb
<head>
        <title>Página Inicial</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= stylesheet_link_tag "style2" %>
        <link rel="shortcut icon" type="image/x-icon" href="/assets/images/icone.png" />
</head>

<body>
        <div class="tudo" id="home">

          <h3>Bem-Vindo à Sua Página</h3>
          <table>
            <tbody>
              <% @usuarios.each do |usuario| %>
                <tr>
                  <td><%= usuario.nome %></td>
                  <td><%= usuario.situacaoMatricula %></td>
                  <td><%= usuario.fotoUsuario %></td>
                  <td><%= usuario.emailUsuario %></td>
                  <td><%= usuario.telefone %></td>
                  <td><%= link_to 'Editar perfil', edit_usuario_path(usuario), id: 'button' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>
        </div>
</body>

Integrado/app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

Integrado/app/views/usuarios/show.html.erb
  <p id="notice"><%= notice %></p>

   <h3>Bem-Vindo à Sua Página</h3>
  <p>
    <strong>Nome:</strong>
    <%= @usuario.nome %>
  </p>

  <p>
    <strong>Último Agendamento:</strong>
    <%= @usuario.ultimoAgendamento %>
  </p>

  <p>
    <strong>Situação de Matrícula:</strong>
    <%= @usuario.situacaoMatricula %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= @usuario.fotoUsuario %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @usuario.emailUsuario %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= @usuario.telefone %>
  </p>

  <%= link_to 'Edit', edit_usuario_path(@usuario), id: 'button' %> |
  <%= link_to 'Back', usuarios_path %>